### ISSUE TITLE
VOTable RESOURCE and TABLE number

### ISSUE THREAD

**Issue by molinaro-m** [ivoa-std/ConeSearch#19]
ConeSearch currently fixes to 1 RESOURCE with 1 TABLE response.
Should this be relaxed?

**Comment by Zarquan** [comment]
Is there a science case for extending this ?

**Comment by molinaro-m** [comment]
The reason to relax this is that, while a single "results" table is fine, the wording in the REC-1.03

`There must be a single RESOURCE in the VOTable, and that contains a single TABLE.`

prevents other RESOURCES even if they were not results one. This blocks the ability to add DataLink service descriptors.

So, it's not to encourage multi-table result sets but to allow RESOURCEs or TABLEs with other goals.
A change in the wording describing this would suffice, in my opinion.

**Comment by molinaro-m** [comment]
Pull request #56, that would be available after #55 refactoring, is supposed to fix this

**Comment by molinaro-m** [comment]
fixed by #56
