### ISSUE TITLE
Move Unified Content Descriptors to UCD1+ standard

### ISSUE THREAD

**Issue by molinaro-m** [ivoa-std/ConeSearch#20]
Although this is definitely a major change in the specification, we should try to move the UCDs listed in the ConeSearch protocol to the UCD1+ syntax.

The following UCD 1.0 words are the only ones used in ConeSearch 1.03:
- ID_MAIN
- POS_EQ_RA_MAIN
- POS_EQ_DEC_MAIN
- OBS_ANG-SIZE

**Comment by molinaro-m** [comment]
A direct move to UCD1+ breaks back-compatibility, on the theoretical level.
In practice, being able to do so for the above 4 UCDs, a lot depends on the ability of client applications to deal with either one UCD format or server/client communication about the supported protocol version.

**Comment by mbtaylor** [comment]
(I am reasonably sure that) TOPCAT etc will not have a problem with cone search services that return UCD1+ instead of UCD1.

**Comment by molinaro-m** [comment]
An investigation on the usage of the UCD / UCD1+ couples in registered ConeSearches

- ID_MAIN / meta.id;meta.main
- POS_EQ_RA_MAIN / pos.eq.ra;meta.main
- POS_EQ_DEC_MAIN / pos.eq.dec;emat.main
- OBS_ANG-SIZE / phys.angSize;obs

shows that there are few cases where the switch to the current UCD Recommendation could lead to issues on the data providers side and, in any case, that those issues are related to the meaning of the "main identifier" for the record in the catalogue, not the update of the UCD specification.
(A few more details are available in [the notes from this DAL running meeting](https://wiki.ivoa.net/internal/IVOA/IvoaDAL_RunningMeetings/IVOA_DAL_RM7_etherpad.txt))

This "main ID" issue will be taken care by a specific repo issue: #53 (main ID usage).

This issue will continue to stay open to further investigate (mainly) client side concerns.

**Comment by molinaro-m** [comment]
Pull Request #58 is supposed to fix and close this issue, pending #55 merge in advance

**Comment by molinaro-m** [comment]
closed via #58
