### ISSUE TITLE
Lack of SR PARAMTER "ALLSKY" value documentation

### ISSUE THREAD

**Issue by Bonnarel** [ivoa-std/ConeSearch#46]
THere is an SR=ALLSKY slot in the Query examples section but nothing appears in the SR subsection (which discusses SR = 0 )

**Comment by molinaro-m** [comment]
I think this was added when adding the TIME interval about a reminder on how to work an all-sky solution that works as a time filter only. This is already under discussion in issue #16 , I suggest to continue the discussion there.

See issue #16
