### ISSUE TITLE
Non-time-aware services

### ISSUE THREAD

**Issue by mbtaylor** [ivoa-std/ConeSearch#47]
I presume that services are not required to be time-aware.

This is alluded to in section 2.1 "The set of query constraints a cone search needs to understand MUST include the RA, DEC, SR parameters, MAY understand the TIME parameter,..." but glossed over elsewhere.

I think it should be spelled out more explicitly elsewhere how the service is expected to behave if it is not time-aware.  How do clients presenting a TIME constraint know if it has been honoured?  Should a non-time-aware service treat a time constraint as an error?

The current text in sec 3.1 (VOTable compliant response) mandates a time column in the output table alongside the ID, RA and Dec columns.  I agree this should be mandatory where the service has performed filtering based on a submitted `TIME` parameter, but I would suggest that it should be optional for non-time-aware services.  If it's mandatory, non-time-aware services may be tempted to put some dummy value in there.

**Comment by Bonnarel** [comment]
Mark makes a good point there. Usual behavior of DAL services when they get a query with a PARAM for which they are not aware is an empty response. And I agree that sec 3.1 constraint should be relaxed.

**Comment by molinaro-m** [comment]
This is not relevant in re-working version 1.1 since it applies to the previous attempt to revision.
Closed.
